version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=api-gateway
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MQTT_URL=mqtt://mosquitto:1883
    ports:
      - "8096:8096"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
    volumes:
      - ./logs/api-gateway:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  compte-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=compte-service
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    volumes:
      - ./logs/compte-service:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  epargne-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=epargne-service
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    volumes:
      - ./logs/epargne-service:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  investissement-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=investissement-service
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    volumes:
      - ./logs/investissement-service:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=supadmin
      - RABBITMQ_DEFAULT_PASS=supadmin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./logs/rabbitmq:/var/log/rabbitmq

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./logs/mosquitto:/mosquitto/log
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -t '$$SYS/#' -C 1 | grep -v Error || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  logrotate:
    image: blacklabelops/logrotate
    volumes:
      - ./logs:/logs
    environment:
      - LOGS_DIRECTORIES=/logs
      - LOGROTATE_INTERVAL=daily
      - LOGROTATE_AMOUNT=7
      - LOGROTATE_SIZE=10M
      - LOGROTATE_COMPRESSION=compress

volumes:
  mosquitto_data:
  mosquitto_log: